apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgCD8fg2vDbBHsx/YtQ8eKu7yYeovOQtwDfUN4Rmf4HAA7XDtsZ9TZCDsC8RjxDH1tD7nlOhKNY9Obh6RSUlKnMPOvPKSZT78vl8QqBCckckDXm5sGmxnUjKt6t49t+jYd128aGjr0SEzWPHppNXUbUUk252d48b3iQmabB2O8YspFS9QfwQQXnSKlV/B/gPJBZCwBiRKJwGU+nflXDy1AmTZpx4GZCB3xrDQCnmlcSoWRYcyI886q4fW1ufPTh8tuWtzXS+tY2Dfqaczl5fTWlY4xybI7HMrM0ZvFCkatzdb0gIvlt5WYsC6o5QMFWykZGph5/BXC7Dfjx+XDtpBQyg5zWUfc/DPtXBiA5H5dxO36RFXKu7yehwvvTGBpaTb/bvvQbvvB6A/uYPWwjTLM3HO9/68hY32574+HH9L+9D5cYM4prx/DDi1J9qJL/GxGDn690FQIblDxXV9UDiQRM4NyCOS9wxyIhv9BBWzd0W+sa6eSZYH///D0QIcE2KrPtqYEP4XVUYyxxHy7+nSxNbkTDI2Lmf1dWUAaf1D1VWOfPTYQBOjoMJ2wXPzBVffmlRrlKyErq7rHGrW6+aMhDkzs6bNsDE8+iyL2Q2tabLGedDktVwBCVcyBGh+VBi/Txnon1bwe8SMNDtukEhHj+/lf6281lVbYi/0DOOm1w+NCCXqA20URAuIkw1AFFmebtU7hNDFk79F2UoN+zI2Z1tY8DbsTHlCLoCREzMag+kWx0cWBlG
    ARTIFACTORY_PASSWORD: AgAIpWiN7zgjN36GhiVpiElel0rtU0yyUneh8Mx+AhjEAs6W2oVjTJfAYIGLod6nf1ydwcFEH5Qr9sMDmlVAy7zuMJ6/y4UX3HCUVE24kXFIuV+d9+7BRRuFZFW8yoxJlubcaB7d+TdojYjagUQwcFApmY4AR69qIoyvAZtHc0PtwD4U/gVGXy7vGDzyDXW9pOOW9DvkDGjeNMNzpb3X9ypSxaQrmbSfEOxXjRx7LmXUPLyzA2rj1p8N1HDbvHln8vHekzANuvrJa4qrQUMOgC84zfri/kAlDoAbXArEiM2LXRkqjS7PXFxWb9Law1j4ZJW4cBz0B4Od7n8OB1WYZZcywVb0Op/U6KhxNzWnWXCsvrbSnO7ulpOkeIWtS2PLxOabo1Na0Lfk4Nv/948ecvN7OjhUG3t6QQp/kDzZfhWMbu9RXf8E6BEVfKz27I3vcJl0a+UTCd/3/K2GbMyVj4R2MCWU9tzkLfmVrJfLiAGCe0fG5gfdXsZ1/rT2pm4lDj3UAu9Rh9gECX07GKHxn2ZjMT+UQT9bl9PiIjjis2Wiu36AaT3rfywzWi3rk8HhlzmFDi6/67CtaLapd38syQNsceohHKk1vu7g8JWgL/ckR3J18MT+dnb1JovxmxuTYJjkAKllBB1hzKucY+22vjTJjpT3XEUiqkuCOweTVGOlK58AJs12AOsv06nfLv3oknIrAYY2zWmcNtFQ4SXzKHxnBB6HuQ==
    ARTIFACTORY_URL: AgC0CcGQBmThgkUNe2rZr6iiimreRPWOHS8gogbI8ofS36PsaLFLZ+lv7Wy93PpDgBC3UNl7tMyzhkb7/H/XBSgdl5xA869YMu1m9mgOR4drrYHRV6OYuhdt1xI4KVzCtLoYkUUHwHxN5qIpIbCL/Rbc9QN2i3wRNLOPCFkWjZC1gxi4uUfZx/h55XK9Hgxx2rDnFcbxppMGiaVS5Fv9TAM5aZxocRKxr1FZ5qkHC7f8YzddxwG7jrvcdu1+tkTXHx2JqJamT/dY6KSwrW/wwwKiq1A4X0cQ0LGpwpAL06rYufLXfqu0Vm9UbZi4V2CIFU92hit2XopzfCO+zHl2fvmP3Ww+BndM0xOI47+bV37X+pN4ZFkVNudY0SvacWXLNNy3UARuNAap7Qu+CO6WrQU6c21bVD7AsPiKEqRJVFtXBYWmKXAuvAyalfzZL8H7EidaX/YAUI/qzmQ1Owsh6AVWscc21AVCpVggkb0cMIKYTcn2vjhXcUIEpY52iKvOZdQRO4oLJidlxb8uF0qIjdnWU47beqosPbHJPscrKoSuxkajNK1AxbQwLGN6f3UVFW5k8R8im5LzjSeln9/9kCSj1VxjvuZIGe2HAPaK3Uk14DI0vl7kh6UFvSAY1OF133u48Ixzsy+ccH4V5BmSDFiXXjx7O9KcakjY84dniNuNMDUW/qbSyiZiJlgO8hUBRG9SPKE7VyCoh2KMKfS2ZJYQCPhMJ56dIU3zC4OEQLWQPeGYhfsl/ejkCg==
    ARTIFACTORY_USER: AgDE7SgnEObi0dmaEAzQO/+xx2ZmfJrWOsMN8nCp1BKYHSGFQai/ZLMGzgbV+TYX2fsF0CF6UqR6nmqOX4bzleu3HY6yGXg2hT5KJSbMZnn7pDb0m62CXuS5nrcr5Sqyrr/3J39IF7F8IDuL+7OX8XxJuxlhn1eS09RlTwqUIzu6V6s8yJ5H4FFCCgl9AHU7MO/u6LZqwRjyPuEhRCYRaypEolfEBj0daoDmfomx8+HUZ00WH0HDn2rzmT94bphgX/T6aULwbM/qQVdkxvKvuZsvrABzCdG7+v3Mntf7o+yONDrlYyizGunudMK8kfqrUu9udUGIXewzW7dv+9tI4kqfO9d4jUJW856Vzxp7XR/YF4yeiBOs/HJTHJIu7D0QnnCv65bEIWJmRGSCRZLn8pJ2DZNedqzWo29N0kCwlr1L5SnnGfI0rowEkAljCRFwk2SttQVwelEXf7VYaRG+NA20rG0+JDLXYIZf8Rm0C0j5NkpiJtXLtKHncMYRgyUxw05sKB9CA8RVdrtMD8eWffxPtpIdu/y3io2gnrjv4ShxsweHvKRhbxsVDuTMCmBz2wQ6KnqmxeLuuaZfghXCTQ+qO1rLhsGCy18XsKv28BX5UcWGmyxdTb/I6i9r40yAoBDu31TCN+BRnB8iDF5M4o+FrCUfB/GNo00ONNbzKhw+cnmdyCOsEV+45VYs2SvwcC28Fy72kg==
  template:
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-10-12T19:15:07Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-10-12T19:16:41Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

